### ISSUE TITLE
Date and Time Pickers not resolved

### ISSUE THREAD

**Issue by lucgirardin** [JetBrains/kotlin-wrappers#1473]
The use of Date and Time Pickers yields the following runtime error:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at Outlet (webpack-internal:///../../node_modules/react-router/index.js:831:26)
    at main
    at eval (webpack-internal:///../../node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at Box (webpack-internal:///../../node_modules/@mui/system/esm/createBox.js:33:72)
    at Routes (webpack-internal:///../../node_modules/react-router/index.js:920:5)
    at eval (webpack-internal:///./kotlin/kotlin_org_jetbrains_kotlin_wrappers_kotlin_react.js:205:14)
    at div
    at eval (webpack-internal:///../../node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at Box (webpack-internal:///../../node_modules/@mui/system/esm/createBox.js:33:72)
    at InnerThemeProvider (webpack-internal:///../../node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:23:70)
    at ThemeProvider (webpack-internal:///../../node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:49:5)
    at ThemeProvider (webpack-internal:///../../node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:43:5)
    at eval (webpack-internal:///./kotlin/kotlin_org_jetbrains_kotlin_wrappers_kotlin_react.js:205:14)
    at eval (webpack-internal:///./kotlin/kotlin_org_jetbrains_kotlin_wrappers_kotlin_react.js:205:14)
    at Router (webpack-internal:///../../node_modules/react-router/index.js:854:15)
    at HashRouter (webpack-internal:///../../node_modules/react-router-dom/index.js:152:5)
    at eval (webpack-internal:///./kotlin/kotlin_org_jetbrains_kotlin_wrappers_kotlin_react.js:205:14)
printWarning @ react.development.js?cfe6:207
error @ react.development.js?cfe6:181
createElementWithValidation @ react.development.js?cfe6:2352
create_0 @ create.kt?67cc:20
invoke_0 @ ChildrenBuilder.kt?d4ac:54
eval @ DateTimePickers.kt?aef6:9
eval @ FC.kt?a0dc:7
createElementOrNull @ Standard.kt?e25e:6
eval @ FC.kt?a0dc:7
renderWithHooks @ react-dom.development.js?f6e0:16175
mountIndeterminateComponent @ react-dom.development.js?f6e0:20913
beginWork @ react-dom.development.js?f6e0:22416
beginWork$1 @ react-dom.development.js?f6e0:27381
performUnitOfWork @ react-dom.development.js?f6e0:26513
workLoopSync @ react-dom.development.js?f6e0:26422
renderRootSync @ react-dom.development.js?f6e0:26390
performConcurrentWorkOnRoot @ react-dom.development.js?f6e0:25694
workLoop @ scheduler.development.js?1ab3:266
flushWork @ scheduler.development.js?1ab3:239
performWorkUntilDeadline @ scheduler.development.js?1ab3:533
```

This can be reproduced by creating the following showcase:

```
val DateTimePickersShowcase = FC<Props> {
    LocalizationProvider {
        DateTimePicker {
        }
    }
}
```

**Comment by lucgirardin** [comment]
Everything work (very) well :-) Thanks a million!
