### ISSUE TITLE
Redux not compatible with serialization 1.0.0-RC2

### ISSUE THREAD

**Issue by rjaros** [JetBrains/kotlin-wrappers#346]
When upgrading serialization to `1.0.0-RC2` I get runtime error from `kotlin-redux`:
```
TypeError: Cannot read property 'Json_x26noe$' of undefined
      at /home/rjaros/git/kvision/build/js/node_modules/kotlin-wrappers-kotlin-redux-jsLegacy/kotlin-wrappers-kotlin-redux-jsLegacy.js:10:1 <- /home/rjaros/git/kvision/build/js/packages/kvision-kvision-redux-test/adapter-browser.js:13364:107
      at Object.../../node_modules/kotlin-wrappers-kotlin-redux-jsLegacy/kotlin-wrappers-kotlin-redux-jsLegacy.js (/home/rjaros/git/kvision/build/js/node_modules/kotlin-wrappers-kotlin-redux-jsLegacy/kotlin-wrappers-kotlin-redux-jsLegacy.js:175:2 <- /home/rjaros/git/kvision/build/js/packages/kvision-kvision-redux-test/adapter-browser.js:13529:2)

```

**Comment by Leonya** [comment]
Released in pre.119
