### ISSUE TITLE
Webpack fails with kotlin-mui 5.0.4 dependency due to missing SwitchBase.js

### ISSUE THREAD

**Issue by mysticfall** [JetBrains/kotlin-wrappers#906]
As of the recent update of `kotlin-mui` to 5.0.4, the Webpack task fails in a project depending on it, due to the fact that `@mui/material/SwitchBase` no longer exists in MUI 5.0.4, which is referenced by the generated Kotlin stubs.

**Comment by mysticfall** [comment]
I just tried the updated version. The change indeed has made my project build and run in a browser again, but now I'm no longer able to run tests (with `useMocha()`) as they fail with the following error:
```
build/js/node_modules/@mui/material/internal/SwitchBase.js:1
import _objectWithoutPropertiesLoose from "@babel/runtime/helpers/esm/objectWithoutPropertiesLoose";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /home/mysticfall/workspace/hseffex-designer/build/js/packages/hseffex-designer-test/kotlin/hseffex-designer-test.js:5:1227
    at Object.<anonymous> (/home/mysticfall/workspace/hseffex-designer/build/js/packages/hseffex-designer-test/kotlin/hseffex-designer-test.js:107:2)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:196:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async formattedImport (/home/mysticfall/workspace/node_modules/mocha/lib/nodejs/esm-utils.js:7:14)
    at async Object.exports.requireOrImport (/home/mysticfall/workspace/node_modules/mocha/lib/nodejs/esm-utils.js:48:32)
    at async Object.exports.loadFilesAsync (/home/mysticfall/workspace/node_modules/mocha/lib/nodejs/esm-utils.js:88:20)
    at async singleRun (/home/mysticfall/workspace/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/home/mysticfall/workspace/node_modules/mocha/lib/cli/run.js:374:5)
```
I'm not entirely certain that it's a bug of this project but it happens when I update the version of kotlin-mui from 5.0.3 to 5.0.5 (with the kotlin-wrappers BOM from 257 to 263) with only minimal changes.

**Comment by mysticfall** [comment]
I just tested it again after updating to the latest snapshot which is based on MUI 5.1.0 but the problem with module import persists.

@turansky Could you look into this issue or point me to a direction that may help me resolving the problem? Thanks!

**Comment by turansky** [comment]
> but the problem with module import persists

In tests only?

**Comment by mysticfall** [comment]
Yes, in test only. The application itself seems to run without problem with `browserDevelopmentRun`. And I suspect it could be specific to Mocha but I'm not really a frontend dev so I'm afraid my experience is not sufficient to easily pinpoint the issue.

**Comment by turansky** [comment]
It looks common problem

**Comment by mysticfall** [comment]
Is there any existing upstream issue, if it's not specific for this project? And if not, could you tell me where should I report the problem?
